### ISSUE TITLE
Deleted Entries are still found

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1094]
I deleted some entries but they are still in the result lists.
This one I think I deleted last week:
https://oerworldmap.org/resource/?q=sade#urn:uuid:9a5de2ae-461d-4986-bd49-a80db3467d3d
This one I think I deleted yesterday:
https://oerworldmap.org/resource/?q=webb#urn:uuid:11118a68-ebaf-4b20-bcba-c74fba87bc3d

**Comment by literarymachine** [comment]
Fixed on production, see https://oerworldmap.org/resource/?q=about.@id:%22urn:uuid:11118a68-ebaf-4b20-bcba-c74fba87bc3d%22 and https://oerworldmap.org/resource/?q=about.@id:%22urn:uuid:9a5de2ae-461d-4986-bd49-a80db3467d3d%22

**Comment by karindr** [comment]
Again there is a deleted entry that is still in the list of search results and also still shown in the recent addition list. It is one of the entries for Schule 4.0:
https://oerworldmap.org/resource/?q=schule#urn:uuid:4cfee78a-05cb-43fb-a877-bd6554064027

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1
