### ISSUE TITLE
Policy stats & recently added policies not shown in German version

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1698]
The recently added functionality for the policy registry
- Kibana statistics 
- recently added policies

is not shown on a Firefox/Windows combination. I tried two different computers:
- Windows 10 Pro Version 10.0.16299 / Firefox 63.0.1 64 Bit
- Windows 7 Professional / Firefox 63.0.1 64 Bit

It works fine with Chrome

**Comment by dobladov** [comment]
This bug is related on how strict is your Firefox policy to include iframes, If you click on the lock on in the url filed you can probably see if Firefox is blocking the content I'm trying to find if there is a way to avoid this on Firefox.

![image](https://user-images.githubusercontent.com/1938043/48337650-cff6aa00-e663-11e8-96fb-e8f03efd242b.png)

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-ui/commit/c416462b72d55bb58982b091274855275471ad58 and https://github.com/hbz/oerworldmap-ui/commit/7318ee5d1357af0be5a8e86d571bd713058e86d4

**Comment by trugwaldsaenger** [comment]
Reopening: Issue still seems not to be solved. On the German version site the iframe code is shown:
![grafik](https://user-images.githubusercontent.com/6639965/48602795-a34cd600-e974-11e8-971b-3145d269108c.png)

**Comment by literarymachine** [comment]
This was fixed, but broken after merging back changes from Crowdin. Apparently because the line break before the `iframe` was removed, very annoying. Fixed again in https://github.com/hbz/oerworldmap-ui/commit/2cec506ddfb2d247ea7268b0eca7ab9d093523bd and https://github.com/hbz/oerworldmap-ui/commit/178153cb2b2461a2d6d02585498afef744bd4aa7.

@acka47 anything we can do to prevent this from happening?

**Comment by acka47** [comment]
> anything we can do to prevent this from happening?

I don't know what happened but my guess it that the next crowding pr will break this again as you changed the file here and not in crowdin...

**Comment by literarymachine** [comment]
If there is no way from prevent Crowdin to remove line breaks, indeed. In some cases, it really isn't really clever; I currently cannot merge https://github.com/hbz/oerworldmap-ui/pull/431/files either.

**Comment by acka47** [comment]
Yes, I know. Crowdin frequently just sucks. I clicked through all the reverted sentences to translate them again. I hope the PR will look better soon.
