### ISSUE TITLE
The Russian exclave of Kaliningrad is sometimes shown as water

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#659]
The Russian exclave of Kaliningrad is sometimes shown as water if the rest of Russia isn’t appearing on the map. You have to zoom in and out and move the map with the mouse to see this effect.

**Comment by j0hj0h** [comment]
Could be a bug in the mapping library or map data, we use. As this could be hard to find and we will switch the mapping library anyway, I would suggest to ignore this so far.

**Comment by karindr** [comment]
By the way, this also happens for French Guiana in South America.

**Comment by acka47** [comment]
Similar to #625. I think, keeping one of both issues is enough...

**Comment by karindr** [comment]
On beta this issue is solved using the new mapping layer. Both exclaves are shown coloured like the connected country. But Kosovo (#625) is still water.

**Comment by literarymachine** [comment]
The current status on beta does not fix this issue in an appropriate way. The subnational boundaries will only be displayed when zooming into an individual country. See #810.
